### ISSUE TITLE
Download is not a .sketchplugin

### ISSUE THREAD

**Issue by smlombardi** [marisaroque/sketch-markup-listify#1]
FYI, when downloading plugin as zip, and unzipping, you get a folder full of files.  Not a .sketchplugin bundle.  Your readme says to double-click the sketchplugin to install but there is none.

I know from experience to add a ".sketchplugin" extension to the folder, click ok on the Finder warning, and then poof there's the sketchplugin.  Double-clicking THAT adds it to Sketch, and then it works fine.

**Comment by marisaroque** [comment]
You are totally right, @smlombardi. I will update the README file right away. Thank you very much for letting me know!

**Comment by marisaroque** [comment]
I think it's fixed now. I'll close the issue. Thank you again!
