### ISSUE TITLE
Better statement

### ISSUE THREAD

**Issue by imhugocom** [marisaroque/sketch-markup-listify#2]
From:

> Markup copied with sucess

To:

> Markup successfully copied

Also note that 'sucess' needs an extra 'c'.

**Comment by imhugocom** [comment]
Found in https://github.com/marisaroque/sketch-markup-listify/blob/master/Markup%20Listify.sketchplugin/Contents/Sketch/markup-listify.js#L42

**Comment by marisaroque** [comment]
Thank you for your feedback, @imhugocom. 

It's better now. 
 https://github.com/marisaroque/sketch-markup-listify/blob/master/Markup%20Listify.sketchplugin/Contents/Sketch/markup-listify.js#L42

I'll close the issue. Thank you again!

**Comment by imhugocom** [comment]
Perfect :)
